#!/bin/bash

# Tabz - Tmux Launch Script
# Starts both backend and frontend in a tmux session

set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$SCRIPT_DIR/backend"
FRONTEND_DIR="$SCRIPT_DIR"

SESSION_NAME="tabz"

echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  Tabz Tmux Launch Script              ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
echo ""

# Interactive configuration
echo -e "${YELLOW}📋 Configuration:${NC}"
echo ""

# Ask about logs window
read -p "$(echo -e ${BLUE}Enable live logs window? ${NC}${YELLOW}[y/N]${NC}: )" ENABLE_LOGS
ENABLE_LOGS=${ENABLE_LOGS:-n}

# Ask about log level if logs enabled
if [[ "$ENABLE_LOGS" =~ ^[Yy]$ ]]; then
  echo ""
  echo -e "${BLUE}Select log level:${NC}"
  echo -e "  ${YELLOW}1${NC} - Silent (no logs)"
  echo -e "  ${YELLOW}2${NC} - Fatal errors only"
  echo -e "  ${YELLOW}3${NC} - Errors and warnings"
  echo -e "  ${YELLOW}4${NC} - Info (default, includes browser console)"
  echo -e "  ${YELLOW}5${NC} - Debug (verbose)"
  echo ""
  read -p "$(echo -e ${BLUE}Log level ${NC}${YELLOW}[1-5, default: 4]${NC}: )" LOG_LEVEL
  LOG_LEVEL=${LOG_LEVEL:-4}

  # Validate log level
  if ! [[ "$LOG_LEVEL" =~ ^[1-5]$ ]]; then
    echo -e "${YELLOW}⚠️  Invalid log level, using 4 (info)${NC}"
    LOG_LEVEL=4
  fi
else
  LOG_LEVEL=4
fi

# Write .env file with selected log level
cat > "$BACKEND_DIR/.env" << EOF
# Tabz Backend Configuration
# Generated by start-tmux.sh

# Logging Configuration
# 0=silent, 1=fatal, 2=error, 3=warn, 4=info, 5=debug
LOG_LEVEL=$LOG_LEVEL
EOF

echo ""
echo -e "${GREEN}✓ Configuration saved${NC}"
echo ""

# Check if tmux is installed
if ! command -v tmux &> /dev/null; then
    echo -e "${RED}❌ tmux is not installed. Please install it first:${NC}"
    echo -e "   ${YELLOW}sudo apt install tmux${NC}"
    exit 1
fi

# Kill existing session if it exists
if tmux has-session -t $SESSION_NAME 2>/dev/null; then
    echo -e "${YELLOW}⚠️  Existing session found. Killing it...${NC}"
    tmux kill-session -t $SESSION_NAME
fi

# Check if backend dependencies are installed
if [ ! -d "$BACKEND_DIR/node_modules" ]; then
    echo -e "${YELLOW}📦 Installing backend dependencies...${NC}"
    cd "$BACKEND_DIR"
    npm install
fi

# Check if frontend dependencies are installed
if [ ! -d "$FRONTEND_DIR/node_modules" ]; then
    echo -e "${YELLOW}📦 Installing frontend dependencies...${NC}"
    cd "$FRONTEND_DIR"
    npm install
fi

echo -e "${GREEN}🚀 Creating tmux session: $SESSION_NAME${NC}"
echo ""

# Create new tmux session with backend in first window
tmux new-session -d -s $SESSION_NAME -n backend -c "$BACKEND_DIR"
tmux send-keys -t $SESSION_NAME:backend "npm start" C-m

# Create frontend window
tmux new-window -t $SESSION_NAME -n frontend -c "$FRONTEND_DIR"
tmux send-keys -t $SESSION_NAME:frontend "npm run dev" C-m

# Create logs window if enabled
if [[ "$ENABLE_LOGS" =~ ^[Yy]$ ]]; then
  tmux new-window -t $SESSION_NAME -n logs -c "$SCRIPT_DIR"
  tmux send-keys -t $SESSION_NAME:logs "echo 'Backend Logs (updating every 1s) - Ctrl+C to stop'; sleep 1; while true; do clear; tmux capture-pane -t $SESSION_NAME:backend -p -S -100; sleep 1; done" C-m
fi

# Select the frontend window
tmux select-window -t $SESSION_NAME:frontend

echo -e "${GREEN}✅ Tabz started in tmux session!${NC}"
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Tmux Commands:${NC}"
echo -e "  Attach:  ${YELLOW}tmux attach -t $SESSION_NAME${NC}"
echo -e "  Detach:  ${YELLOW}Ctrl+B, then D${NC}"
if [[ "$ENABLE_LOGS" =~ ^[Yy]$ ]]; then
  echo -e "  Windows: ${YELLOW}Ctrl+B, then 0/1/2${NC} (backend/frontend/logs)"
else
  echo -e "  Windows: ${YELLOW}Ctrl+B, then 0/1${NC} (backend/frontend)"
fi
echo -e "  Kill:    ${YELLOW}tmux kill-session -t $SESSION_NAME${NC}"
echo ""
echo -e "${BLUE}URLs:${NC}"
echo -e "  Frontend: ${YELLOW}http://localhost:5173${NC}"
echo -e "  Backend:  ${YELLOW}http://localhost:8127${NC}"
echo ""
echo -e "${BLUE}Log Level: ${YELLOW}$LOG_LEVEL${NC} ${NC}(0=silent, 1=fatal, 2=error, 3=warn, 4=info, 5=debug)"
if [[ "$ENABLE_LOGS" =~ ^[Yy]$ ]]; then
  echo -e "${BLUE}Live Logs: ${GREEN}Enabled${NC}"
else
  echo -e "${BLUE}Live Logs: ${YELLOW}Disabled${NC} (backend logs still visible in window 0)"
fi
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}Attaching to tmux session...${NC}"
echo ""

# Attach to the session
tmux attach -t $SESSION_NAME
